# Generated by Django 5.0.1 on 2024-02-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('dni', models.CharField(default='000000000', max_length=12)),
                ('sexo', models.CharField(choices=[('O', 'Otro'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1)),
                ('legajo', models.CharField(default='-----', max_length=20, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Curso: ')),
                ('imagen', models.ImageField(default=None, null=True, upload_to='', verbose_name='Imagen')),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Los Cursos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('dni', models.CharField(default='000000000', max_length=12)),
                ('sexo', models.CharField(choices=[('O', 'Otro'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1)),
                ('cuit', models.CharField(max_length=100, verbose_name='Cuit')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('turno', models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], default=3)),
                ('portada', models.ImageField(null=True, upload_to='imagenes/comisiones/', verbose_name='Portada')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.docente')),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Cursando'), (3, 'Egresado')], default=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comision')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.AddField(
            model_name='comision',
            name='alumnos',
            field=models.ManyToManyField(through='core.Inscripcion', to='core.alumno'),
        ),
    ]
