# Generated by Django 5.0.1 on 2024-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_curso_options_alumno_sexo_alter_alumno_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('O', 'Otro'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1),
        ),
    ]
