# Generated by Django 5.0.1 on 2024-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alumno_dni_alter_alumno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
