# Generated by Django 5.0.1 on 2024-02-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curso_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='pago_primera_cuota',
            new_name='activo',
        ),
    ]
