# Generated by Django 5.0.1 on 2024-02-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_pago_primera_cuota_alumno_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='legajo',
            field=models.CharField(default='-----', max_length=20, null=True),
        ),
    ]
