# Generated by Django 5.0.1 on 2024-02-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alumno_legajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='edad',
        ),
    ]
