# Generated by Django 5.0.1 on 2024-02-15 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_alumno_curso_remove_alumno_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('dni', models.CharField(default='000000000', max_length=12)),
                ('sexo', models.CharField(choices=[('O', 'Otro'), ('M', 'Masculino'), ('F', 'Femenino')], default='O', max_length=1)),
                ('cuit', models.CharField(max_length=100, verbose_name='Cuit')),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('portada', models.ImageField(null=True, upload_to='imagenes/comisiones/', verbose_name='Portada')),
                ('alumnos', models.ManyToManyField(to='core.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.docente')),
            ],
            options={
                'verbose_name_plural': 'Comisiones',
            },
        ),
    ]
