# Generated by Django 5.0.1 on 2024-02-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_docente_alter_alumno_options_curso_baja_comision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='turno',
        ),
        migrations.AddField(
            model_name='comision',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Noche')], default=3),
        ),
    ]
